project:
  type: book

book:
  title: "eLatim v1.2.200"
  author: "Lucas Consolin Dezotti"
  date: "11/27/2025"
  chapters:
  - index.qmd
  - references.qmd
  - ab.qmd
  - accipio.qmd
  - ad.qmd
  - ago.qmd
  - aliquis.qmd
  - alius.qmd
  - alter.qmd
  - amicus.qmd
  - an.qmd
  - animus.qmd
  - annus.qmd
  - apud.qmd
  - arma.qmd
  - at.qmd
  - atque.qmd
  - audio.qmd
  - aut.qmd
  - autem.qmd
  - bellum.qmd
  - bene.qmd
  - bonum.qmd
  - bonus.qmd
  - Caesar.qmd
  - capio.qmd
  - castra.qmd
  - causa.qmd
  - ceterus.qmd
  - ciuis.qmd
  - ciuitas.qmd
  - cognosco.qmd
  - consilium.qmd
  - consul.qmd
  - corpus.qmd
  - credo.qmd
  - cum.qmd
  - cum2.qmd
  - de.qmd
  - debeo.qmd
  - deinde.qmd
  - deus.qmd
  - dico.qmd
  - dies.qmd
  - do.qmd
  - dominus.qmd
  - domus.qmd
  - dum.qmd
  - duo.qmd
  - ego.qmd
  - enim.qmd
  - eo.qmd
  - ergo.qmd
  - et.qmd
  - et2.qmd
  - etiam.qmd
  - ex.qmd
  - exercitus.qmd
  - facio.qmd
  - fero.qmd
  - fides.qmd
  - filius.qmd
  - fio.qmd
  - fortuna.qmd
  - genus.qmd
  - gero.qmd
  - grauis.qmd
  - habeo.qmd
  - hic.qmd
  - hinc.qmd
  - homo.qmd
  - hostis.qmd
  - iam.qmd
  - idem.qmd
  - igitur.qmd
  - ille.qmd
  - imperium.qmd
  - in.qmd
  - inquam.qmd
  - inter.qmd
  - ipse.qmd
  - is.qmd
  - iste.qmd
  - ita.qmd
  - itaque.qmd
  - iubeo.qmd
  - iudex.qmd
  - iudicium.qmd
  - ius.qmd
  - legio.qmd
  - lex.qmd
  - licet.qmd
  - locus.qmd
  - magis.qmd
  - magnus.qmd
  - manus.qmd
  - meus.qmd
  - miles.qmd
  - mitto.qmd
  - modo.qmd
  - modus.qmd
  - mors.qmd
  - mos.qmd
  - multus.qmd
  - nam.qmd
  - natura.qmd
  - ne.qmd
  - ne3.qmd
  - nec.qmd
  - nemo.qmd
  - neque.qmd
  - nihil.qmd
  - nisi.qmd
  - nomen.qmd
  - non.qmd
  - nos.qmd
  - noster.qmd
  - nouus.qmd
  - nullus.qmd
  - nunc.qmd
  - omnis.qmd
  - pars.qmd
  - parum.qmd
  - paruus.qmd
  - pater.qmd
  - pecunia.qmd
  - per.qmd
  - periculum.qmd
  - peto.qmd
  - pono.qmd
  - populus.qmd
  - possum.qmd
  - primum.qmd
  - primus.qmd
  - pro.qmd
  - publicus.qmd
  - puto.qmd
  - qua.qmd
  - qua2.qmd
  - quaero.qmd
  - quantus.qmd
  - que.qmd
  - qui.qmd
  - quia.qmd
  - quidam.qmd
  - quidem.qmd
  - quis.qmd
  - quisquam.qmd
  - quisque.qmd
  - quod.qmd
  - ratio.qmd
  - refero.qmd
  - relinquo.qmd
  - res.qmd
  - rex.qmd
  - romanus.qmd
  - saepe.qmd
  - scio.qmd
  - scribo.qmd
  - sed.qmd
  - semper.qmd
  - senatus.qmd
  - sequor.qmd
  - si.qmd
  - sic.qmd
  - sine.qmd
  - sui.qmd
  - sum.qmd
  - super.qmd
  - suus.qmd
  - tam.qmd
  - tamen.qmd
  - tantus.qmd
  - tempus.qmd
  - teneo.qmd
  - terra.qmd
  - totus.qmd
  - tu.qmd
  - tum.qmd
  - tuus.qmd
  - ubi.qmd
  - uel.qmd
  - uenio.qmd
  - uerbum.qmd
  - uero.qmd
  - uerus.qmd
  - uester.qmd
  - uideo.qmd
  - uinco.qmd
  - uir.qmd
  - uirtus.qmd
  - uis.qmd
  - uita.qmd
  - uiuo.qmd
  - ullus.qmd
  - unus.qmd
  - uoco.qmd
  - uolo.qmd
  - uos.qmd
  - uox.qmd
  - urbs.qmd
  - ut.qmd
  - ut2.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4





