---
title: "cum2"
format: html
editor: visual
toc: false
---


```{r  setUp, include=FALSE}
 library(tidyverse) 

      EntryData <- readRDS(paste0("./", dir("./")[str_detect(dir("./"), "_xx99-117-109-50xx_.rds")]))

```


#### bases lexicais

&emsp;






::: panel-tabset

#### LiLa Lemma Bank

<small> id: </small> <a href=' http://lila-erc.eu/data/id/lemma/97201 ' target="_blank"> http://lila-erc.eu/data/id/lemma/97201 </a> <br>
<small> classe: </small> preposição    <br>
<small> paradigma: </small> indeclinável <br>
<small> outras grafias: </small> com, con, cun, qum, quom <br>
<small> variantes do lema: </small>  <br>





#### PrinParLat

no data




#### Lexicala

no data




#### WordNet

no data


:::



#### dicionários tradicionais

&emsp;




::: panel-tabset

#### Faria

<small>1</small> <b>cum</b> <br> <small>prep. abl.</small> <br> <small></small>   <p> <b>1</b> &ensp; <small></small> &ensp; Com, em companhia de, juntamente com &ensp; <small>ideia de companhia Cíc. At. 8, 2, 3.</small> <br> <b>2</b> &ensp; <small></small> &ensp; Com, logo que &ensp; <small>indicando simultaneidade no tempo:</small> <br> <b>3</b> &ensp; <small></small> &ensp; Com &ensp; <small>ideia de modo ou maneira de ser, qualificado:</small> <br> <b>4</b> &ensp; <small></small> &ensp; Com &ensp; <small>ideia de instrumento:</small> </p>   <p><small>[EXEMPLOS]</small><br> <br><b>2</b><br>cum prima luce Cíc. At. 4, 3, 4 “ao raiar do dia, logo que amanhece”: exit cum nuntio Cés. B. Gal. 5, 46, 3 «sai logo que recebe a notícia”. <br> <br><b>3</b><br>magno cum lucto Cíc. Verr. 4, 76 “com grande dor”. <br> <br><b>4</b><br>cum lingua lingere Catul. 98, 3 “lamber com a língua”. </p>




#### Saraiva

no data




#### Fonseca

<b>Cum</b> <br> <small>prep. de abl.</small>   <p> <b>1</b> &ensp; <small>Cic.</small> &ensp; com, juntamente, em companhia. </p>




#### Velez

<b>Cum</b> <br> <small>Praepos.</small> <br> <small>In his: Mecum, Tecum, Secum, Vobiscum, Nobiscum, Quibuscum, suo casui postponitur. Vide tum.</small>   <p> <b>1</b> &ensp; com </p>




#### Cardoso

<b>Cum</b> <br> <small>praepositio.</small>   <p> <b>1</b> &ensp; com </p>


:::



#### dados de corpus

&emsp;




::: panel-tabset

#### Possíveis colocados

no data




#### substantivos

no data




#### adjetivos

no data




#### verbos

no data




#### advérbios

no data




#### preposições e conjunções

no data


:::



::: panel-tabset

#### Frequência por autor

no data




#### Frequência por gênero

no data




#### Frequência por século

no data




#### ExemplosTraduzidos

no data


:::



#### Diagrama de Zipf

no data


