# Prefácio {.unnumbered}

Bem vindo ao **eLatim**.

Nesta versão, este dicionário digital latim-português fornece dados e informações sobre as mil palavras mais frequentes do léxico latino, combinando lexicografia tradicional, lexicografia computacional e linguística de corpus.

Cada verbete é uma página Web dividida em três seções.

A primeira apresenta o conteúdo de **dicionários tradicionais** a respeito de cada lema. Nesta versão, quatro dicionários foram incluídos: o *Dicionário Escolar Latino-Português* [@faria1994dicionario], o *Parvum lexicum latinum lusitana interpretatione adjecta* [@fonseca1798pdf], o *Index totius artis* [@velez1744pdf] e o *Dictionarium latino lusitanicum* [@cardoso1570pdf]; além desses, foi incluída uma pequena amostra do *Novissimo Diccionario Latino-Portuguez* [@saraiva1927dic], correspondente aos onze verbos mais frequentes em latim (a saber, *ago*, *dico*, *do*, *facio*, *fero*, *habeo*, *possum*, *sum*, *uideo*, *uenio*, *uolo*).

A segunda traz dados obtidos de diversas **bases lexicais** dedicadas ao latim.
O *LiLa Lemma Bank* [@passarotti2020interlinking] fornece classificação gramatical e morfológica, bem como informação sobre formação, grafias alternativas e variantes do lema.
O *Latin Core Vocabulary* [@francese2020core] fornece significado básico, classificação semântica e ranking de frequência.
O *PrinParLat* [@pellegrini2023prinparlat] e o *Lexicala* [kernerman2018introducing] são dois recursos que trazem formas tradicionalmente utilizadas como bases para a flexão dos lemas: o primeiro fornece as formas principais para a conjugação dos verbos, o segundo as formas canônicas tradicionais de todos os lemas, marcadas com indicação prosódica completa (longas e breves).
Por fim, a aba *WordNet* resulta de um cruzamento de dados entre a *Latin WordNet* [@minozzi2017latin, @franzini2019nunc] e duas wordnets do português [a saber, @rademaker2012openwordnet, @simoes2016enriching].

A terceira traz **dados de corpus**, extraídos de um conjunto de textos latinos datados do período clássico (i.e., entre os séculos I a.C. e I d.C.) -- excetuando-se uma pequena amostra da *Vulgata* --, com um total de 292 mil palavras distribuídas por 16,5 mil sentenças.
Nessa seção, um primeiro conjunto de abas traz uma tabela com os principais candidatos a colocados do lema, obtidos por cálculos estatísticos, seguida de visualizações gráficas (no formato nuvem de palavras) desses colocados, divididos por classe de palavras.
Já o segundo conjunto de abas oferece exemplos diretamente extraídos dos textos (com base no modelo GDEx), acompanhados de uma tradução do Prof. José Dejalma Dezotti feita inicialmente para uso particular e gentilmente cedida para compor este dicionário.

O dicionário é resultado de uma pesquisa de doutorado realizada no Programa de Pós-Graduação em Linguística e Língua Portuguesa da Faculdade de Ciências e Letras da UNESP, em Araraquara, e contou com apoio da Coordenação de Aperfeiçoamento de Pessoal de Nível Superior - CAPES/Brasil (Código de Financiamento 001).

Comentários e sugestões são sempre bem-vindos, escrever para [lucas.dezotti@academico.ufpb.br](mailto:lucas.dezotti@academico.ufpb.br).

Bom proveito,

Lucas Dezotti

--------------------------------------------
REFERÊNCIAS