---
title: "ne3"
format: html
editor: visual
toc: false
---


```{r  setUp, include=FALSE}
 library(tidyverse) 

      EntryData <- readRDS(paste0("./", dir("./")[str_detect(dir("./"), "_xx110-101-51xx_.rds")]))

```


#### bases lexicais

&emsp;






::: panel-tabset

#### LiLa Lemma Bank

<small> id: </small> <a href=' http://lila-erc.eu/data/id/lemma/113490 ' target="_blank"> http://lila-erc.eu/data/id/lemma/113490 </a> <br>
<small> classe: </small> advérbio    <br>
<small> paradigma: </small> indeclinável <br>
<small> outras grafias: </small>  <br>
<small> variantes do lema: </small>  <br>





#### PrinParLat

no data




#### Lexicala

<b> nē </b> <br> <b> nĕ </b> <br />




#### WordNet

no data


:::



#### dicionários tradicionais

&emsp;




::: panel-tabset

#### Faria

<small>1</small> <b>nē</b> <br> <small>adv. de afirmação</small> <br> <small>Obs.: Ne é uma partícula afirmativa, geralmente empregada na língua da conversação, antes de um pron. pessoal ou demonstrativo.</small>   <p> <b>1</b> &ensp; <small></small> &ensp; Certamente, sim &ensp; <small>Plaut. Men. 899.</small> </p> 
 <small>2</small> <b>nĕ</b> <br> <small>adv. de negação, arcaico</small> <br> <small>Obs.: Ocorre como primeiro elemento de numerosos compostos: nec, neque, neuter, nemo, etc.</small>   <p> <b>1</b> &ensp; <small>= non, mas nunca aparece isolado.</small> &ensp; Não: &ensp; <small></small> </p>   <p><small>[EXEMPLOS]</small><br> <br><b>1</b><br>nevolt Plaut. Most. 110 «não quer» </p> 
 <small>3</small> <b>nē</b> <br> <small>adv. e conj. negativa. I. Adv.</small> <br> <small></small>   <p> <b>1</b> &ensp; <small></small> &ensp; Não. Nas orações independentes exprime: &ensp; <small></small> <br> <b>2</b> &ensp; <small></small> &ensp; Nem ... sequer &ensp; <small>ne... quidem:</small> </p>   <p><small>[EXEMPLOS]</small><br> <br><b>1</b><br>a Proibição com imperativo, nos textos de lei, ou subjuntivo: ne audeto Cíc. Leg. 2, 22 “não ouse”: Plaut. Pers. 490; Verg. En. 6, 832: T. Lív. 3, 2, 9; ne repugnetis Cic. Clu. 6 “não resistais”: hoc ne feceris Cíc. Div. 2, 127 “não faças isto”; b suposição ou concessão: ne sint in senectute vires Cíc. C. M. 34 “admitamos que: não haja forças na velhice”; c desejo: ne istuc Juppiter sirit T. Lív. 28, 28, 11 “que Júpiter não o permita”. <br> <br><b>2</b><br>ne sues quidem Cíc. Tusc. 1, 92 «nem sequer os porcos». </p>




#### Saraiva

no data




#### Fonseca

<b>Ne</b> <br> <small>adv.</small>   <p> <b>1</b> &ensp; <small>Cic.</small> &ensp; não <br> <b>3</b> &ensp; <small>Cic.</small> &ensp; nem. </p>




#### Velez

<b>Ne</b> <br> <small>Adverb.</small>   <p> <b>1</b> &ensp; naõ <br> <b>2</b> &ensp; <small>interdum pro Neque, sequente Quidem, ita ut aliquid intercedat</small> </p>   <p><small>[EXEMPLOS]</small><br> <br><b>2</b><br>ne nunc quidem &ensp; <small>nem ainda agora</small> <br> <br><b>X</b><br>ne plura. Ne multa, uel Ne multis &ensp; <small><small>subaudito dicam, vel aliud simile</small></small> </p>




#### Cardoso

<b>Ne</b> <br> <small>aduerb. vetandi.</small>   <p> <b>1</b> &ensp; não </p>


:::



#### dados de corpus

&emsp;




::: panel-tabset

#### Possíveis colocados

no data




#### substantivos

no data




#### adjetivos

no data




#### verbos

no data




#### advérbios

no data




#### preposições e conjunções

no data


:::



::: panel-tabset

#### Frequência por autor

no data




#### Frequência por gênero

no data




#### Frequência por século

no data




#### ExemplosTraduzidos

no data


:::



#### Diagrama de Zipf

no data


