---
title: "ut2"
format: html
editor: visual
toc: false
---


```{r  setUp, include=FALSE}
 library(tidyverse) 

      EntryData <- readRDS(paste0("./", dir("./")[str_detect(dir("./"), "_xx117-116-50xx_.rds")]))

```


#### bases lexicais

&emsp;






::: panel-tabset

#### LiLa Lemma Bank

<small> id: </small> <a href=' http://lila-erc.eu/data/id/lemma/130905 ' target="_blank"> http://lila-erc.eu/data/id/lemma/130905 </a> <br>
<small> classe: </small> advérbio    <br>
<small> paradigma: </small> indeclinável <br>
<small> outras grafias: </small> utei, uti <br>
<small> variantes do lema: </small>  <br>





#### PrinParLat

no data




#### Lexicala

<b> ŭt </b> <br />




#### WordNet

no data


:::



#### dicionários tradicionais

&emsp;




::: panel-tabset

#### Faria

<b>ut</b> <br> <b>uti</b> <br> <small>adv. e conj. I. Adv.</small> <br> <small></small>   <p> <b>1</b> &ensp; <small></small> &ensp; Como, de que modo, de que maneira: &ensp; <small></small> <br> <b>2</b> &ensp; <small></small> &ensp; Assim como, como, do mesmo modo &ensp; <small>em correlação com sic, ou ita:</small> <br> <b>3</b> &ensp; <small></small> &ensp; Como, de que modo &ensp; <small>nas interrogações diretas ou indiretas, e nas exclamações:</small> <br> <b>4</b> &ensp; <small></small> &ensp; Que, oxalá &ensp; <small>com o subjuntivo optativo:</small> </p>   <p><small>[EXEMPLOS]</small><br> <br><b>1</b><br>Ciceronem et ut rogas, amo, et ut meretur, et ut debeo Cíc. Q. Fr. 3, 9, 9 “amo teu filho Cícero como me pedes, como ele merece e como devo”: Cíc. Ac. 2. 69: Cíc. Fin. 4, 51. <br> <br><b>2</b><br>ut optasti, ita est CÍc. Fam. 2, 10 “é assim como o desejaste”: Pomponium Atticum sic amo, ut alterum fratrem Cíc. Fam. 13,1 “gosto de Pompônio Ático assim como de um segundo irmão”. <br> <br><b>3</b><br>ut vales? Plaut. Most. 718 ‘como vais?’; videmusne, ut pueri aliquid scire se gaudeant? Cíc. Fin. 5, 48 ‘não vemos como as crianças gostam de saber alguma coisa?’ quae ut sustinuit! Cíc. Mil. 64 “como suportou estas coisas!”. <br> <br><b>4</b><br>ut te di deaeque perduint Ter. Heaut. 810 “que ou oxalá os deuses e as deusas causem a tua perda”. </p> 
 <small>1</small> <b>utī</b> <br> <small></small> <br> <small>v. ut.</small> 
 <small>2</small> <b>utĭquĕ</b> <br> <small>= et uti e et ut.</small> <br> <small></small>




#### Saraiva

no data




#### Fonseca

<b>Ut</b> <br> <small>adv.</small>   <p> <b>1</b> &ensp; <small>Cic.</small> &ensp; assim como, como. <br> <b>2</b> &ensp; da maneira que, de que modo. <br> <b>3</b> &ensp; segundo, conforme. <br> <b>4</b> &ensp; porque. <br> <b>5</b> &ensp; tanto que, despois que, logo que. <br> <b>6</b> &ensp; que. </p>   <p><small>[EXEMPLOS]</small><br> <br><b>X</b><br>ut mea memoria est &ensp; <small><small>Cic</small></small> &ensp; <small>Segundo me lembro</small> <br> ut plurimum &ensp; <small><small>Cic</small></small> &ensp; <small>Quando muito, ao mais</small> <br> ut uere dicam &ensp; <small><small>Cic</small></small> &ensp; <small>A dizer a verdade</small> </p> 
 <b>Uti</b> <br> <small>conj.</small>   <p> <b>1</b> &ensp; <small>Plaut.</small> &ensp; como. </p>




#### Velez

<b>Ut</b> <br> <small>Adverb.</small>   <p> <b>1</b> &ensp; depois que, como, assim como, praza a Deos </p> 
 <b>Uti</b> <br> <small>Adverb.</small>   <p> <b>1</b> &ensp; assim como </p>




#### Cardoso

<b>Vti</b> <br> <small>particula.</small>   <p> <b>1</b> &ensp; assi como </p>


:::



#### dados de corpus

&emsp;




::: panel-tabset

#### Possíveis colocados

no data




#### substantivos

no data




#### adjetivos

no data




#### verbos

no data




#### advérbios

no data




#### preposições e conjunções

no data


:::



::: panel-tabset

#### Frequência por autor

no data




#### Frequência por gênero

no data




#### Frequência por século

no data




#### ExemplosTraduzidos

no data


:::



#### Diagrama de Zipf

no data


